### ISSUE TITLE
Plotting yaw and roll angles

### ISSUE THREAD

**Issue by sarmadm** [chili-epfl/attention-tracker#20]
HI

I have question , I want to draw yaw angles and roll , how can I do something like this image : [ head pose plot ](http://pasteboard.co/aa8AzOz8B.png)

**Comment by severin-lemaignan** [comment]
You can find such an example in the gazr fork: https://github.com/severin-lemaignan/gazr/commit/fc26ca28ec5859f78ae4bd1969ec41dd457a3da4

**Comment by sarmadm** [comment]
I compiled gazr and attention tracker . for attentatio tracker it works fine with this command : ./head_pose_test ../share/shape_predictor_68_face_landmarks.dat . 

but with gazr this error shows : 
opengl support available 
(ERROR)icvOpenAVI_XINE(): Unable to initialize video driver.
Couldn't open camera

when I tried to run live_plot.py  : 

./estimate_gaze_direction -c --model=shape_predictor_68_face_landmarks.dat | python -u live_plot.py

this error shows : 

tofi@tofi:~/gazr/build$ ./estimate_gaze_direction -c --model=shape_predictor_68_face_landmarks.dat | python -u live_plot.py
bash: ./estimate_gaze_direction: No such file or directory
python: can't open file 'live_plot.py': [Errno 2] No such file or directory

**Comment by severin-lemaignan** [comment]
@sarmadm These are basic mistakes, and I fear that github issues are not the right place to teach about the basics of computer science... that said:
- `gazr` is a *fork* of `attention_tracker`: they do the same thing. If you launch both, one will fail as only one process can access the webcam at a time. In your case, do not start `attention_tracker`. Only use `gazr`.
- python does not find `live_plot.py` because you are not in the right directory. `$ ./estimate_gaze_direction -c --model=shape_predictor_68_face_landmarks.dat | python -u ../tools/live_plot.py` should work.

**Comment by sarmadm** [comment]
@severin-lemaignan , thanks for comments . I run only gazr , not both of them .

when I run gazr it fails to initilatize my webcam : 
(ERROR)icvOpenAVI_XINE(): Unable to initialize video driver.
Couldn't open camera

but when I run attention_ tracker there is no problems .

**Comment by sarmadm** [comment]
When I run :

tofi@tofi:~/gazr-master/build$ ./estimate_gaze_direction -c --model=shape_predictor_68_face_landmarks.dat | python -u ../tools/live_plot.py


bash: ./estimate_gaze_direction: No such file or directory
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/tofi/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "../tools/live_plot.py", line 22, in <module>
    data = eval(line)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
